telemetry = false

[run]
silent = true

[install]
minimumReleaseAge = 172800

minimumReleaseAgeExcludes = [
  "@astrojs/telemetry",
  "@types/bun",
  "@types/node",
  "astro",
  "bun-types",
  "typescript",
]